Repository NVIDIA/bionemo-framework, pull requests merged in 2024-11, with the labels that each got.

#232 Pydantic Configs and execution.
  README.md
  scripts/protein/esm2/esm2_pretrain.py
  scripts/protein/esm2/test_esm2_pretrain.py
  scripts/protein/esm2/test_pydantic_train.py
  sub-packages/bionemo-core/src/bionemo/core/utils/dtypes.py
  sub-packages/bionemo-esm2/pyproject.toml
  sub-packages/bionemo-esm2/src/bionemo/esm2/data/datamodule.py
  sub-packages/bionemo-esm2/src/bionemo/esm2/model/model.py
  sub-packages/bionemo-esm2/src/bionemo/esm2/run/__init__.py
  sub-packages/bionemo-esm2/src/bionemo/esm2/run/config_models.py
  sub-packages/bionemo-esm2/src/bionemo/esm2/run/main.py
  sub-packages/bionemo-esm2/src/bionemo/esm2/run/recipes.py
  sub-packages/bionemo-esm2/tests/bionemo/esm2/model/test_stop_and_go.py
  sub-packages/bionemo-geneformer/pyproject.toml
  sub-packages/bionemo-geneformer/src/bionemo/geneformer/run/__init__.py
  sub-packages/bionemo-geneformer/src/bionemo/geneformer/run/config_models.py
  sub-packages/bionemo-geneformer/src/bionemo/geneformer/run/main.py
  sub-packages/bionemo-geneformer/src/bionemo/geneformer/run/recipes.py
  sub-packages/bionemo-geneformer/src/bionemo/geneformer/scripts/train_geneformer.py
  sub-packages/bionemo-geneformer/tests/bionemo/geneformer/scripts/test_pydantic_train.py
  sub-packages/bionemo-llm/src/bionemo/llm/model/biobert/model.py
  sub-packages/bionemo-llm/src/bionemo/llm/model/lr_scheduler.py
  sub-packages/bionemo-llm/src/bionemo/llm/run/__init__.py
  sub-packages/bionemo-llm/src/bionemo/llm/run/config_models.py
  sub-packages/bionemo-llm/src/bionemo/llm/train.py
  sub-packages/bionemo-llm/src/bionemo/llm/utils/logger_utils.py
  sub-packages/bionemo-llm/tests/bionemo/llm/model/test_lr_scheduler.py
Labels: NOT_related_to_v24.10

#390 Polinabinder/scdl document
  sub-packages/bionemo-scdl/README.md
Labels: documentation, SKIP_CI

#416 fix: remove text key with custom font value (solves stylesheet verify…
  docs/mkdocs.yml
Labels: documentation, SKIP_CI

#380 Update default mike config
  docs/mkdocs.yml
Labels: documentation, SKIP_CI

#418 Update minimum driver version
  docs/docs/user-guide/getting-started/pre-reqs.md
Labels: documentation, SKIP_CI

#413 Fix release notes links from v1.x and update broken `site:` links
  docs/docs/models/esm2.md
  docs/docs/user-guide/appendix/releasenotes-fw.md
  docs/docs/user-guide/background/nemo2.md
Labels: documentation, SKIP_CI

#417 Update command to pull latest BioNeMo1 tag
  docs/bionemo/access-startup.md
Labels: documentation, SKIP_CI

#381 mount netrc file for wandb inside devcontainer
  .devcontainer/devcontainer.json
Labels: SKIP_CI

#431 re-enable merge groups to trigger blossom-ci
  .github/workflows/blossom-ci.yml
Labels: SKIP_CI

#446 Update the title for DSMBind doc
  docs/bionemo/models/dsmbind.md
Labels: SKIP_CI

#447 Add documentation and release info to README
  README.md
Labels: documentation, SKIP_CI

#455 Update error prone stop/go atol to more stable setting
  sub-packages/bionemo-core/tests/bionemo/core/data/test_load.py
  sub-packages/bionemo-geneformer/tests/bionemo/geneformer/test_stop_and_go.py
Labels: bug

#462 Cache dev build from our nightly public container
  internal/scripts/build_dev_image.sh
Labels: SKIP_CI

#449 BugFix: fix bugs on bionemo-size-aware-batching
  sub-packages/bionemo-size-aware-batching/src/bionemo/size_aware_batching/sampler.py
  sub-packages/bionemo-size-aware-batching/tests/bionemo/size_aware_batching/test_sampler.py
Labels: bug

#470 Fix typos in geneformer benchmark description
  docs/docs/user-guide/examples/bionemo-geneformer/geneformer-celltype-classification.ipynb
Labels: documentation, SKIP_CI

#483 Updating Brev.Dev documentation
  .secrets-nb.baseline
  docs/docs/user-guide/examples/bionemo-esm2/inference.ipynb
  docs/docs/user-guide/examples/bionemo-esm2/mutant-design.ipynb
  docs/docs/user-guide/examples/bionemo-esm2/pretrain.md
  docs/docs/user-guide/getting-started/access-startup.md
  sub-packages/bionemo-example_model/README.md
  sub-packages/bionemo-scdl/examples/example_notebook.ipynb
Labels: documentation, SKIP_CI

#468 Add release notes for v2.1
  docs/docs/user-guide/appendix/releasenotes-fw.md
Labels: documentation, SKIP_CI

#488 Update VERSION
  VERSION
Labels: documentation, SKIP_CI

#453 Atom and bond features
  sub-packages/bionemo-geometric/pyproject.toml
  sub-packages/bionemo-geometric/src/bionemo/geometric/atom_featurizers.py
  sub-packages/bionemo-geometric/src/bionemo/geometric/base_featurizer.py
  sub-packages/bionemo-geometric/src/bionemo/geometric/bond_featurizers.py
  sub-packages/bionemo-geometric/src/bionemo/geometric/data/electronic_data.csv
  sub-packages/bionemo-geometric/tests/bionemo/geometric/test_atom_featurizers.py
  sub-packages/bionemo-geometric/tests/bionemo/geometric/test_bond_featurizers.py
Labels: enhancement
