Repository NVIDIA/bionemo-framework, pull requests merged in 2024-10, with the labels that each got.

#360 Update mkdocs.yml
  docs/mkdocs.yml
Labels: documentation

#364 Improve ESM2 pretraining VDR
  docs/docs/user-guide/examples/bionemo-esm2/pretrain.md
Labels: documentation, SKIP_CI

#367 change ESM2 to ESM-2 in written docs
  docs/docs/datasets/uniprot.md
  docs/docs/models/esm2.md
  docs/docs/user-guide/appendix/releasenotes-fw.md
  docs/docs/user-guide/examples/bionemo-esm2/finetune.md
  docs/docs/user-guide/examples/bionemo-esm2/pretrain.md
  docs/docs/user-guide/getting-started/development.md
  sub-packages/bionemo-testing/src/bionemo/testing/data/README.md
Labels: SKIP_CI

#377 Add docs on MegatronDataModule and WrappedDataLoader
  docs/docs/user-guide/background/megatron_datasets.md
Labels: documentation, SKIP_CI

#388 Revert "Savitha/integrate scdl into geneformer megatron compatible"
  scripts/singlecell/geneformer/test_train.py
  scripts/singlecell/geneformer/train.py
  sub-packages/bionemo-geneformer/pyproject.toml
  sub-packages/bionemo-geneformer/src/bionemo/geneformer/data/singlecell/datamodule.py
  sub-packages/bionemo-geneformer/src/bionemo/geneformer/data/singlecell/dataset.py
  sub-packages/bionemo-geneformer/tests/bionemo/geneformer/conftest.py
  sub-packages/bionemo-geneformer/tests/bionemo/geneformer/test_dataset.py
  sub-packages/bionemo-geneformer/tests/bionemo/geneformer/test_model.py
  sub-packages/bionemo-geneformer/tests/bionemo/geneformer/test_stop_and_go.py
  sub-packages/bionemo-testing/src/bionemo/testing/data/resources/scdl_feature_ids.yaml
  sub-packages/bionemo-testing/src/bionemo/testing/data/resources/single_cell.yaml
  tach.toml
Labels: SKIP_CI
