Repository NVIDIA/bionemo-framework, pull requests merged in 2025-01, with the labels that each got.

#569 run pytest with or without docs and notebooks in run_pytest.sh
  .github/pull_request_template.md
  .github/workflows/pr-labels.yml
  ci/scripts/run_pytest.sh
  docs/docs/user-guide/contributing/contributing.md
Labels: INCLUDE_NOTEBOOKS_TESTS

#562 remove unused file from repo
  docs/docs/docs.todo
Labels: documentation, SKIP_CI

#577 Edits to README and CONTRIBUTING.md, moving some text around
  README.md
  docs/docs/user-guide/contributing/contributing.md
  docs/docs/user-guide/getting-started/SUMMARY.md
  docs/docs/user-guide/getting-started/development.md
  docs/docs/user-guide/getting-started/training-models.md
  internal/scripts/README.md
Labels: SKIP_CI

#586 Add gpu target identificator to JET configs
  ci/benchmarks/partial-conv/esm2_pretrain.yaml
  ci/benchmarks/perf/esm2_pretrain.yaml
Labels: SKIP_CI

#588 add codecov badge
  .github/workflows/pre-commit.yml
  .github/workflows/unit-tests.yml
  README.md
Labels: SKIP_CI

#521 Remove outdated note on very large datasets in MultiEpochDataset
  docs/docs/user-guide/background/megatron_datasets.md
  docs/docs/user-guide/getting-started/index.md
Labels: SKIP_CI

#600 fix esm2_pretrain.yaml
  ci/benchmarks/partial-conv/esm2_pretrain.yaml
Labels: SKIP_CI

#594 add myself to ci
  .github/workflows/blossom-ci.yml
Labels: SKIP_CI, ready

#595 Only run cleanup if tests ran, adds pytest marker config for slow tests
  .github/pull_request_template.md
  .github/workflows/pr-labels.yml
  .github/workflows/unit-tests.yml
  .secrets.baseline
  pyproject.toml
Labels: INCLUDE_NOTEBOOKS_TESTS, ready

#602 Remove v2.0 from README title
  README.md
Labels: SKIP_CI

#584 fix image links in esm2 model card
  docs/docs/assets/images/esm2/esm2_device_scaling.png
  docs/docs/assets/images/esm2/esm2_model_scaling.png
  docs/docs/assets/images/esm2/esm2_model_scaling.svg
  docs/docs/assets/images/esm2/esm2_pretrain_convergence.png
  docs/docs/assets/images/esm2/esm2_single_node_training_perf.png
  docs/docs/models/ESM-2/index.md
  docs/docs/models/ESM-2/pre-training.md
  docs/docs/models/index.md
Labels: SKIP_CI

#610 fix devcontainer paths in ubuntu 24
  .devcontainer/devcontainer.json
Labels: SKIP_CI

#617 Jm/codeowners revamp
  .github/workflows/approvals.yml
  CODEOWNERS
Labels: SKIP_CI

#614 Update MoCo notebooks
  sub-packages/bionemo-moco/examples/continuous_data_interpolant_tutorial.ipynb
  sub-packages/bionemo-moco/examples/discrete_data_interpolant_tutorial.ipynb
  sub-packages/bionemo-moco/src/bionemo/moco/interpolants/discrete_time/discrete/d3pm.py
  sub-packages/bionemo-moco/tests/bionemo/moco/interpolants/discrete_time/discrete/test_d3pm.py
Labels: INCLUDE_NOTEBOOKS_TESTS

#627 Adds bionemno-esm2 section to CODEOWNERS
  CODEOWNERS
Labels: SKIP_CI

#636 remove PerplexityCallback in pydantic api
  sub-packages/bionemo-llm/src/bionemo/llm/run/config_models.py
  sub-packages/bionemo-llm/src/bionemo/llm/train.py
Labels: bug

#635 catch ngc api key validation errors and default to not using an api key
  sub-packages/bionemo-core/src/bionemo/core/data/load.py
  sub-packages/bionemo-core/tests/bionemo/core/data/test_load.py
Labels: bug

#641 2.3 (25.01) release notes
  docs/docs/user-guide/appendix/releasenotes-fw.md
Labels: SKIP_CI

#637 Don't upload merge queue results to codecov
  .github/workflows/unit-tests.yml
Labels: bug

#648 fix devcontainer initialize script
  .devcontainer/initializeCommand.sh
Labels: bug, SKIP_CI

#649 Fix geneformer notebook tests by removing 10m_bnmo2 model
  docs/docs/user-guide/examples/bionemo-geneformer/geneformer-celltype-classification.ipynb
Labels: INCLUDE_NOTEBOOKS_TESTS

#651 Mark geneformer test_pretrain_cli as slow
  sub-packages/bionemo-geneformer/tests/bionemo/geneformer/scripts/test_train_geneformer.py
Labels: SKIP_CI

#650 edit to approval workflow to avoid marking a failed action
  .github/workflows/approvals.yml
Labels: SKIP_CI

#634 added slow test label and execute full testing suite before merge
  .github/pull_request_template.md
  .github/workflows/unit-tests.yml
  docs/docs/user-guide/contributing/contributing.md
  sub-packages/bionemo-esm2/tests/bionemo/esm2/model/test_convert.py
Labels: INCLUDE_NOTEBOOKS_TESTS

#647 templates for bugs and feature requests
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: SKIP_CI

#638 Instructions for uploading a package to pypi
  internal/Pypi_publish.md
Labels: documentation, SKIP_CI

#656 add options for pytest duration logging
  .github/workflows/unit-tests.yml
  ci/scripts/run_pytest.sh
  pyproject.toml
Labels: INCLUDE_NOTEBOOKS_TESTS, INCLUDE_SLOW_TESTS

#632 Update MoCo Version and MDLM params
  CODEOWNERS
  sub-packages/bionemo-moco/README.md
  sub-packages/bionemo-moco/VERSION
  sub-packages/bionemo-moco/documentation.md
  sub-packages/bionemo-moco/examples/continuous_data_interpolant_tutorial.ipynb
  sub-packages/bionemo-moco/src/bionemo/moco/interpolants/continuous_time/continuous/continuous_flow_matching.py
  sub-packages/bionemo-moco/src/bionemo/moco/interpolants/continuous_time/discrete/mdlm.py
  sub-packages/bionemo-moco/src/bionemo/moco/interpolants/discrete_time/continuous/ddpm.py
  sub-packages/bionemo-moco/src/bionemo/moco/schedules/discrete_noise_schedules.py
  sub-packages/bionemo-moco/tests/bionemo/moco/interpolants/continuous_time/continuous/test_continuous_flow_matching.py
  sub-packages/bionemo-moco/tests/bionemo/moco/interpolants/continuous_time/discrete/test_mdlm.py
  sub-packages/bionemo-moco/tests/bionemo/moco/schedules/noise/test_continuous_noise_transforms.py
  sub-packages/bionemo-moco/tests/bionemo/moco/schedules/noise/test_continuous_snr_transforms.py
  sub-packages/bionemo-moco/tests/bionemo/moco/schedules/test_discrete_noise_schedules.py
Labels: INCLUDE_NOTEBOOKS_TESTS

#666 Fix nightly container link in README
  README.md
Labels: SKIP_CI

#668 update issue templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: SKIP_CI

#665 improve readme
  README.md
Labels: documentation, SKIP_CI
