Repository NVIDIA/bionemo-framework, pull requests merged in 2025-05, with the labels that each got.

#796 fix Evo2 training crash - TE commit
  Dockerfile
Labels: INCLUDE_NOTEBOOKS_TESTS, INCLUDE_SLOW_TESTS

#859 add wandb group and model size in Geneformer configs: benchmarks
  ci/benchmarks/partial-conv/geneformer_pretrain.yaml
  ci/benchmarks/perf/geneformer_pretrain.yaml
Labels: SKIP_CI

#860 Skip d3pm notebook tests on B200
  sub-packages/bionemo-moco/VERSION
  sub-packages/bionemo-moco/documentation.md
  sub-packages/bionemo-moco/examples/discrete_data_interpolant_tutorial.ipynb
  sub-packages/bionemo-moco/src/bionemo/moco/interpolants/continuous_time/discrete/mdlm.py
Labels: INCLUDE_NOTEBOOKS_TESTS

#866 upgrade pytorch to 25.04
  Dockerfile
Labels: INCLUDE_NOTEBOOKS_TESTS, INCLUDE_SLOW_TESTS

#840 Set EXPERIMENTAL_1b_CHECKPOINT to True by default
  sub-packages/bionemo-evo2/examples/zeroshot_brca1.ipynb
Labels: INCLUDE_NOTEBOOKS_TESTS

#878 Fix missing context in ESM2 FT checkpoint
  docs/docs/user-guide/examples/bionemo-esm2/finetune.ipynb
  sub-packages/bionemo-esm2/src/bionemo/esm2/scripts/finetune_esm2.py
Labels: INCLUDE_NOTEBOOKS_TESTS

#879 Jwilber/1413 unify nb locations
  docs/README.md
  docs/docs/SUMMARY.md
  docs/docs/main/SUMMARY.md
  docs/docs/main/about/SUMMARY.md
  docs/docs/main/about/background/SUMMARY.md
  docs/docs/main/about/background/megatron_datasets.md
  docs/docs/main/about/background/nemo2.md
  docs/docs/main/about/overview.md
  docs/docs/main/about/releasenotes-fw.md
  docs/docs/main/contributing/Writing Documentation/index.md
  docs/docs/main/contributing/Writing Documentation/jupyter-notebooks.ipynb
  docs/docs/main/contributing/Writing Documentation/mkdocs.md
  docs/docs/main/contributing/code-review.md
  docs/docs/main/contributing/contributing.md
  docs/docs/main/contributing/sub-package_dependency_graph.md
  docs/docs/main/datasets/CELLxGENE.md
  docs/docs/main/datasets/index.md
  docs/docs/main/datasets/uniprot.md
  docs/docs/main/developer-guide/SUMMARY.md
  docs/docs/main/examples/.gitignore
  docs/docs/main/examples/SUMMARY.md
  docs/docs/main/examples/conftest.py
  docs/docs/main/getting-started/SUMMARY.md
  docs/docs/main/getting-started/access-startup.md
  docs/docs/main/getting-started/development.md
  docs/docs/main/getting-started/index.md
  docs/docs/main/getting-started/initialization-guide.md
  docs/docs/main/getting-started/pre-reqs.md
  docs/docs/main/getting-started/training-models.md
  docs/docs/main/getting-started/using-slurm.md
  docs/docs/main/index.md
  docs/docs/main/references/API_reference/index.md
  docs/docs/main/references/FAQ.md
  docs/docs/models/index.md
  docs/docs/user-guide/SUMMARY.md
  docs/docs/user-guide/examples/bionemo-geneformer/geneformer-celltype-classification.ipynb
  docs/docs/user-guide/examples/bionemo-geneformer/geneformer_cellxgene_tutorial.ipynb
  docs/docs/user-guide/getting-started/pre-reqs.md
  docs/scripts/gen_ref_pages.py
  sub-packages/bionemo-esm2/examples/finetune.ipynb
  sub-packages/bionemo-esm2/examples/inference.ipynb
  sub-packages/bionemo-esm2/examples/mutant-design.ipynb
  sub-packages/bionemo-esm2/examples/pretrain.md
  sub-packages/bionemo-geneformer/examples/.gitignore
  sub-packages/bionemo-geneformer/examples/geneformer-celltype-classification.ipynb
  sub-packages/bionemo-geneformer/examples/geneformer_cellxgene_tutorial.ipynb
Labels: documentation, SKIP_CI, INCLUDE_NOTEBOOKS_TESTS

#829 Fixes how num_layers relates to pipeline_model_parallel_size in ESM2
  ci/benchmarks/perf/esm2_pretrain.yaml
  sub-packages/bionemo-esm2/src/bionemo/esm2/scripts/train_esm2.py
Labels: bug, ESM2

#891 Fix broken links and add banner
  docs/docs/index.md
  docs/overrides/main.html
Labels: documentation, SKIP_CI

#837 Add small section mentioning context extension
  sub-packages/bionemo-evo2/README.md
Labels: SKIP_CI
