Repository NVIDIA/bionemo-framework, pull requests merged in 2025-09, with the labels that each got.

#1034 update root README.md for open file count error
  README.md
Labels: documentation, good first issue

#943 Add Unit Test for Genformer Training Script
  sub-packages/bionemo-geneformer/tests/bionemo/geneformer/scripts/test_train_geneformer.py
  sub-packages/bionemo-testing/src/bionemo/testing/tensorboard.py
Labels: INCLUDE_SLOW_TESTS

#1162 Update VERSION for scdl
  sub-packages/bionemo-scdl/VERSION
  sub-packages/bionemo-scdl/pyproject.toml
Labels: SKIP_CI, ciflow:skip

#1157 switch to 25.08 for unit tests
  .devcontainer/recipes/Dockerfile
  .github/workflows/unit-tests-recipes.yml
  bionemo-recipes/models/esm2/Dockerfile
  bionemo-recipes/recipes/README.md
  bionemo-recipes/recipes/amplify_accelerate_te_fp8/Dockerfile
  bionemo-recipes/recipes/esm2_accelerate_te/Dockerfile
  bionemo-recipes/recipes/esm2_native_te/Dockerfile
  bionemo-recipes/recipes/esm2_native_te_mfsdp_thd/Dockerfile
  bionemo-recipes/recipes/geneformer_native_te_mfsdp_fp8/Dockerfile
  bionemo-recipes/recipes/vit/Dockerfile
  ci/scripts/recipes_local_test.py
Labels: INCLUDE_ALL_RECIPES

#1156 bug template - adding instructions how to get git commit hash
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: ciflow:skip

#1186 ensure branch resolves correctly for commit_sha
  ci/lepton/model_convergence/scripts/wrap_template.sh
Labels: ciflow:skip

#1187 Refactor convergence test gh action to allow for gpu selection
  .github/workflows/convergence-tests.yml
Labels: ciflow:skip

#1032 Add Mamba model support to Evo2 performance benchmarks
  ci/benchmarks/partial-conv/evo2_pretrain.yaml
  ci/benchmarks/perf/evo2_pretrain.yaml
Labels: ciflow:skip

#1197 Jwilber/update esm2 native te.yaml
  ci/lepton/model_convergence/configs/base.yaml
  ci/lepton/model_convergence/configs/recipes/esm2_accelerate_te.yaml
  ci/lepton/model_convergence/configs/recipes/esm2_native_te.yaml
  ci/lepton/model_convergence/scripts/launch_job.py
  ci/lepton/model_convergence/scripts/wrap_template.sh
Labels: ciflow:skip

#1211 remove esm2_native_te_mfsdp_thd option and reorder ui options
  .github/workflows/convergence-tests.yml
Labels: ciflow:skip
