Repository NVIDIA/bionemo-framework, pull requests merged in 2025-07, with the labels that each got.

#965 Fix test_train_evo2_stops test
  sub-packages/bionemo-evo2/tests/bionemo/evo2/run/test_train.py
Labels: INCLUDE_NOTEBOOKS_TESTS, INCLUDE_SLOW_TESTS

#981 Update Docs Banner for GitHub Pages-hosted Docs
  docs/overrides/main.html
Labels: documentation, SKIP_CI

#971 Add release notes for v2.6.2 (25.06)
  docs/docs/main/about/releasenotes-fw.md
Labels: SKIP_CI

#987 [BIONEMO-2334] Patch TE to fix Evo2 stop and go training
  Dockerfile
  patches/te.patch
  sub-packages/bionemo-evo2/tests/bionemo/evo2/run/test_train.py
Labels: INCLUDE_NOTEBOOKS_TESTS, INCLUDE_SLOW_TESTS

#994 Fix bug in evo2-mamba train and add test
  sub-packages/bionemo-evo2/src/bionemo/evo2/run/train.py
  sub-packages/bionemo-evo2/tests/bionemo/evo2/run/test_train.py
Labels: bug

#1002 fix esm2 finetuning tutorial
  sub-packages/bionemo-esm2/examples/finetune.ipynb
Labels: documentation, SKIP_CI

#1009 update codeowners
  CODEOWNERS
Labels: SKIP_CI, ciflow:skip

#1003 update evo2 zero shot notebook
  sub-packages/bionemo-evo2/examples/zeroshot_brca1.ipynb
Labels: documentation, SKIP_CI
