Repository NVIDIA/bionemo-framework, pull requests merged in 2025-06, with the labels that each got.

#894 Final documentation edits
  docs/docs/main/about/background/megatron_datasets.md
  docs/docs/main/about/background/nemo2.md
  docs/docs/main/getting-started/access-startup.md
  sub-packages/bionemo-example_model/README.md
  sub-packages/bionemo-moco/README.md
Labels: documentation, SKIP_CI

#915 Turn on chatbot visibility by default
  docs/docs/assets/css/chatbot.css
Labels: documentation, SKIP_CI

#909 fix typo in pretrain.md
  sub-packages/bionemo-esm2/examples/pretrain.md
Labels: documentation, SKIP_CI

#808 Geneformer gene embeddings calculation. Now limits the changes to bionemo.geneformer only
  sub-packages/bionemo-geneformer/examples/geneformer-gene-embedding-GRN.ipynb
  sub-packages/bionemo-geneformer/examples/geneformer_cellxgene_tutorial.ipynb
  sub-packages/bionemo-geneformer/src/bionemo/geneformer/scripts/infer_geneformer.py
  sub-packages/bionemo-geneformer/src/bionemo/geneformer/utils/__init__.py
  sub-packages/bionemo-geneformer/src/bionemo/geneformer/utils/callbacks.py
Labels: INCLUDE_NOTEBOOKS_TESTS

#923 Fix broken image links in cellgene
  docs/docs/main/datasets/CELLxGENE.md
Labels: documentation, SKIP_CI

#929 Reduce number of training steps for partial-conv: esm2
  ci/benchmarks/partial-conv/esm2_pretrain.yaml
Labels: SKIP_CI

#889 test stage specific run_pytest* files to standardise how tests are run in CIs
  .github/workflows/unit-tests.yml
  ci/scripts/pytest_runner.sh
  ci/scripts/run_pytest_notebooks.sh
  ci/scripts/run_pytest_slow.sh
  ci/scripts/run_pytest_unittests.sh
  internal/scripts/README.md
Labels: INCLUDE_NOTEBOOKS_TESTS, INCLUDE_SLOW_TESTS

#947 Cye/fix test pypi publish
  .github/workflows/bionemo-subpackage-ci.yml
Labels: SKIP_CI

#950 fix bug that didn't load the head
  sub-packages/bionemo-esm2/src/bionemo/esm2/scripts/infer_esm2.py
  sub-packages/bionemo-esm2/tests/bionemo/esm2/scripts/test_infer_esm2.py
Labels: bug
