Repository NVIDIA/bionemo-framework, pull requests merged in 2025-03, with the labels that each got.

#722 Pstjohn/trufflehog move action 2
  .github/workflows/trufflehog.yml
Labels: SKIP_CI

#727 JET for evo2: 1b model training
  ci/benchmarks/partial-conv/evo2_pretrain.yaml
  ci/benchmarks/perf/evo2_pretrain.yaml
Labels: SKIP_CI

#724 GTC Evo2 Demo Notebooks
  .devcontainer/devcontainer.json
  .devcontainer/initializeCommand.sh
  .github/workflows/unit-tests.yml
  docs/README.md
  docs/docs/user-guide/examples/bionemo-evo2/evo2_zeroshot_brca.ipynb
  docs/docs/user-guide/examples/bionemo-evo2/fine-tuning-tutorial.ipynb
  docs/mkdocs.yml
  docs/scripts/gen_ref_pages.py
  sub-packages/bionemo-evo2/examples/.gitignore
  sub-packages/bionemo-evo2/examples/assets/1b_finetuning_train_curve_500_steps_256gbs.png
  sub-packages/bionemo-evo2/examples/fine-tuning-tutorial.ipynb
  sub-packages/bionemo-evo2/examples/zeroshot_brca1.ipynb
  sub-packages/bionemo-evo2/src/bionemo/evo2/run/predict.py
  sub-packages/bionemo-evo2/src/bionemo/evo2/run/train.py
Labels: INCLUDE_NOTEBOOKS_TESTS

#752 Update brev.dev badges to launchable built off main branch
  sub-packages/bionemo-evo2/examples/fine-tuning-tutorial.ipynb
  sub-packages/bionemo-evo2/examples/zeroshot_brca1.ipynb
Labels: INCLUDE_NOTEBOOKS_TESTS

#756 hotfix: docker build in CI
  ci/scripts/build_docker_image.sh
Labels: SKIP_CI

#755 updated version for 2.5 release
  VERSION
Labels: SKIP_CI

#736 update evo2 partial conv max steps
  ci/benchmarks/partial-conv/evo2_pretrain.yaml
Labels: SKIP_CI

#758 Updated file paths for images in SCDL README
  docs/scripts/gen_ref_pages.py
  sub-packages/bionemo-scdl/README.md
  sub-packages/bionemo-scdl/assets/disk_space.png
  sub-packages/bionemo-scdl/assets/throughput.png
Labels: documentation, SKIP_CI

#761 hotfix CI: failing test test_train_evo2_stops
  sub-packages/bionemo-evo2/tests/bionemo/evo2/run/test_train.py
Labels: Evo2

#764 adding v2.5 release notes
  docs/docs/user-guide/appendix/releasenotes-fw.md
Labels: SKIP_CI

#772 Remove Evo2 PR announcement now that everything is merged
  README.md
Labels: documentation, SKIP_CI

#779 [hotfix] setting as "ignore" the failing notebook geneformer_cellxgene_tutorial.ipynb
  docs/conftest.py
Labels: INCLUDE_NOTEBOOKS_TESTS

#783 Remove outdated evo2 tutorial that is now in the submodule
  docs/docs/user-guide/examples/bionemo-evo2/fine-tuning-tutorial.ipynb
Labels: documentation, SKIP_CI

#789 Pin griffe to 1.6.2
  docs/requirements.txt
Labels: SKIP_CI
